version: '3.8'

services:
  frontend:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/app
      # Use a named volume for node_modules to avoid overwriting with local node_modules
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - VITE_API_PROXY_TARGET=http://backend:3001
    depends_on:
      - backend
    # Keep the container running
    tty: true
    # Enable hot reloading
    stdin_open: true

  backend:
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/app
      # Use a named volume for node_modules to avoid overwriting with local node_modules
      - backend_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      # Add other environment variables needed for the backend
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecoestate
    # command: npm run dev
    # Uncomment and configure database service if needed
    # depends_on:
    #   - db

  # Uncomment this section if you need a database
  # db:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=ecoestate
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  frontend_node_modules:
  backend_node_modules:
  # Uncomment if using database
  # postgres_data: 
