name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify a Node.js version compatible with your project
          cache: "npm"
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
      - name: Install Dependencies - Client
        run: npm ci --prefix client
      - name: Install Dependencies - Server
        run: npm ci --prefix server
      - name: Run ESLint - Client
        run: npm run lint --prefix client
      - name: Run ESLint - Server
        run: npm run lint --prefix server

  tfsec:
    name: TFsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run TFsec Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: tf
          # Add any other tfsec flags if needed, e.g., --tfvars-file or --exclude
